### ISSUE TITLE
Can you can't?

### ISSUE THREAD

**Issue by zoltan-levay-epam** [bencevarga666/bencevarga666.github.io#6]
Miserable margins, crestfallen case sizes, the good ol' default color pallet of MS PowerPoint and even the js generated shapes behind the title are pixelated. Holy shit man, you done got yourself some quality meme material here. Keep up the good work.

**Comment by bencevarga666** [comment]
Those are not 'miserable' margins, those are free (as speech) margins. They do whatever they want. The color scheme is not any form of MS PowerPoint derivatives, but randomly picked from the internet, because it is obvious that I don't have any taste. And well, the pseudo-random-generated-JS-shapes-on-HTML5-canvas has been bought from a 11 years old script kiddie, I'm naturally disabled to use such advanced technologies.

Thank you for letting me know about your new Github account, I'm really proud of you as your mummy is.
